use LagashBackOffice;
SET IDENTITY_INSERT Pais ON
INSERT INTO Pais (IdPais,ISO,Descripcion)VALUES(1, 'AF', 'Afganistán');
INSERT INTO Pais (IdPais,ISO,Descripcion)  VALUES(2, 'AX', 'Islas Gland');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(3, 'AL', 'Albania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(4, 'DE', 'Alemania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(5, 'AD', 'Andorra');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(6, 'AO', 'Angola');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(7, 'AI', 'Anguilla');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(8, 'AQ', 'Antártida');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(9, 'AG', 'Antigua y Barbuda');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(10, 'AN', 'Antillas Holandesas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(11, 'SA', 'Arabia Saudí');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(12, 'DZ', 'Argelia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(13, 'AR', 'Argentina');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(14, 'AM', 'Armenia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(15, 'AW', 'Aruba');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(16, 'AU', 'Australia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(17, 'AT', 'Austria');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(18, 'AZ', 'Azerbaiyán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(19, 'BS', 'Bahamas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(20, 'BH', 'Bahréin');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(21, 'BD', 'Bangladesh');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(22, 'BB', 'Barbados');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(23, 'BY', 'Bielorrusia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(24, 'BE', 'Bélgica');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(25, 'BZ', 'Belice');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(26, 'BJ', 'Benin');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(27, 'BM', 'Bermudas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(28, 'BT', 'Bhután');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(29, 'BO', 'Bolivia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(30, 'BA', 'Bosnia y Herzegovina');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(31, 'BW', 'Botsuana');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(32, 'BV', 'Isla Bouvet');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(33, 'BR', 'Brasil');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(34, 'BN', 'Brunéi');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(35, 'BG', 'Bulgaria');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(36, 'BF', 'Burkina Faso');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(37, 'BI', 'Burundi');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(38, 'CV', 'Cabo Verde');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(39, 'KY', 'Islas Caimán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(40, 'KH', 'Camboya');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(41, 'CM', 'Camerún');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(42, 'CA', 'Canadá');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(43, 'CF', 'República Centroafricana');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(44, 'TD', 'Chad');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(45, 'CZ', 'República Checa');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(46, 'CL', 'Chile');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(47, 'CN', 'China');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(48, 'CY', 'Chipre');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(49, 'CX', 'Isla de Navidad');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(50, 'VA', 'Ciudad del Vaticano');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(51, 'CC', 'Islas Cocos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(52, 'CO', 'Colombia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(53, 'KM', 'Comoras');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(54, 'CD', 'República Democrática del Congo');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(55, 'CG', 'Congo');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(56, 'CK', 'Islas Cook');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(57, 'KP', 'Corea del Norte');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(58, 'KR', 'Corea del Sur');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(59, 'CI', 'Costa de Marfil');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(60, 'CR', 'Costa Rica');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(61, 'HR', 'Croacia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(62, 'CU', 'Cuba');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(63, 'DK', 'Dinamarca');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(64, 'DM', 'Dominica');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(65, 'DO', 'República Dominicana');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(66, 'EC', 'Ecuador');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(67, 'EG', 'Egipto');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(68, 'SV', 'El Salvador');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(69, 'AE', 'Emiratos Árabes Unidos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(70, 'ER', 'Eritrea');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(71, 'SK', 'Eslovaquia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(72, 'SI', 'Eslovenia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(73, 'ES', 'España');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(75, 'US', 'Estados Unidos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(76, 'EE', 'Estonia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(77, 'ET', 'Etiopía');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(78, 'FO', 'Islas Feroe');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(79, 'PH', 'Filipinas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(80, 'FI', 'Finlandia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(81, 'FJ', 'Fiyi');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(82, 'FR', 'Francia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(83, 'GA', 'Gabón');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(84, 'GM', 'Gambia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(85, 'GE', 'Georgia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(87, 'GH', 'Ghana');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(88, 'GI', 'Gibraltar');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(89, 'GD', 'Granada');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(90, 'GR', 'Grecia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(91, 'GL', 'Groenlandia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(92, 'GP', 'Guadalupe');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(93, 'GU', 'Guam');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(94, 'GT', 'Guatemala');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(95, 'GF', 'Guayana Francesa');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(96, 'GN', 'Guinea');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(97, 'GQ', 'Guinea Ecuatorial');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(98, 'GW', 'Guinea-Bissau');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(99, 'GY', 'Guyana');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(100, 'HT', 'Haití');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(101, 'HM', 'Islas Heard y McDonald');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(102, 'HN', 'Honduras');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(103, 'HK', 'Hong Kong');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(104, 'HU', 'Hungría');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(105, 'IN', 'India');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(106, 'ID', 'Indonesia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(107, 'IR', 'Irán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(108, 'IQ', 'Iraq');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(109, 'IE', 'Irlanda');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(110, 'IS', 'Islandia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(111, 'IL', 'Israel');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(112, 'IT', 'Italia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(113, 'JM', 'Jamaica');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(114, 'JP', 'Japón');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(115, 'JO', 'Jordania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(116, 'KZ', 'Kazajstán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(117, 'KE', 'Kenia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(118, 'KG', 'Kirguistán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(119, 'KI', 'Kiribati');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(120, 'KW', 'Kuwait');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(121, 'LA', 'Laos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(122, 'LS', 'Lesotho');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(123, 'LV', 'Letonia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(124, 'LB', 'Líbano');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(125, 'LR', 'Liberia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(126, 'LY', 'Libia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(127, 'LI', 'Liechtenstein');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(128, 'LT', 'Lituania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(129, 'LU', 'Luxemburgo');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(130, 'MO', 'Macao');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(131, 'MK', 'ARY Macedonia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(132, 'MG', 'Madagascar');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(133, 'MY', 'Malasia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(134, 'MW', 'Malawi');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(135, 'MV', 'Maldivas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(136, 'ML', 'Malí');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(137, 'MT', 'Malta');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(138, 'FK', 'Islas Malvinas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(139, 'MP', 'Islas Marianas del Norte');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(140, 'MA', 'Marruecos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(141, 'MH', 'Islas Marshall');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(142, 'MQ', 'Martinica');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(143, 'MU', 'Mauricio');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(144, 'MR', 'Mauritania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(145, 'YT', 'Mayotte');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(146, 'MX', 'México');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(147, 'FM', 'Micronesia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(148, 'MD', 'Moldavia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(149, 'MC', 'Mónaco');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(150, 'MN', 'Mongolia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(151, 'MS', 'Montserrat');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(152, 'MZ', 'Mozambique');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(153, 'MM', 'Myanmar');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(154, 'NA', 'Namibia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(155, 'NR', 'Nauru');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(156, 'NP', 'Nepal');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(157, 'NI', 'Nicaragua');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(158, 'NE', 'Níger');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(159, 'NG', 'Nigeria');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(160, 'NU', 'Niue');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(161, 'NF', 'Isla Norfolk');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(162, 'NO', 'Noruega');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(163, 'NC', 'Nueva Caledonia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(164, 'NZ', 'Nueva Zelanda');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(165, 'OM', 'Omán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(166, 'NL', 'Países Bajos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(167, 'PK', 'Pakistán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(168, 'PW', 'Palau');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(169, 'PS', 'Palestina');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(170, 'PA', 'Panamá');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(171, 'PG', 'Papúa Nueva Guinea');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(172, 'PY', 'Paraguay');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(173, 'PE', 'Perú');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(174, 'PN', 'Islas Pitcairn');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(175, 'PF', 'Polinesia Francesa');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(176, 'PL', 'Polonia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(177, 'PT', 'Portugal');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(178, 'PR', 'Puerto Rico');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(179, 'QA', 'Qatar');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(180, 'GB', 'Reino Unido');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(181, 'RE', 'Reunión');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(182, 'RW', 'Ruanda');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(183, 'RO', 'Rumania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(184, 'RU', 'Rusia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(185, 'EH', 'Sahara Occidental');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(186, 'SB', 'Islas Salomón');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(187, 'WS', 'Samoa');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(188, 'AS', 'Samoa Americana');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(189, 'KN', 'San Cristóbal y Nevis');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(190, 'SM', 'San Marino');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(191, 'PM', 'San Pedro y Miquelón');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(192, 'VC', 'San Vicente y las Granadinas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(193, 'SH', 'Santa Helena');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(194, 'LC', 'Santa Lucía');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(195, 'ST', 'Santo Tomé y Príncipe');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(196, 'SN', 'Senegal');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(197, 'CS', 'Serbia y Montenegro');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(198, 'SC', 'Seychelles');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(199, 'SL', 'Sierra Leona');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(200, 'SG', 'Singapur');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(201, 'SY', 'Siria');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(202, 'SO', 'Somalia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(203, 'LK', 'Sri Lanka');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(204, 'SZ', 'Suazilandia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(205, 'ZA', 'Sudáfrica');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(206, 'SD', 'Sudán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(207, 'SE', 'Suecia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(208, 'CH', 'Suiza');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(209, 'SR', 'Surinam');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(210, 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(211, 'TH', 'Tailandia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(212, 'TW', 'Taiwán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(213, 'TZ', 'Tanzania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(214, 'TJ', 'Tayikistán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(215, 'IO', 'Territorio Británico del Océano Índico');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(216, 'TF', 'Territorios Australes Franceses');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(217, 'TL', 'Timor Oriental');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(218, 'TG', 'Togo');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(219, 'TK', 'Tokelau');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(220, 'TO', 'Tonga');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(221, 'TT', 'Trinidad y Tobago');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(222, 'TN', 'Túnez');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(223, 'TC', 'Islas Turcas y Caicos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(224, 'TM', 'Turkmenistán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(225, 'TR', 'Turquía');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(226, 'TV', 'Tuvalu');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(227, 'UA', 'Ucrania');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(228, 'UG', 'Uganda');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(229, 'UY', 'Uruguay');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(230, 'UZ', 'Uzbekistán');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(231, 'VU', 'Vanuatu');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(232, 'VE', 'Venezuela');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(233, 'VN', 'Vietnam');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(234, 'VG', 'Islas Vírgenes Británicas');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(236, 'WF', 'Wallis y Futuna');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(237, 'YE', 'Yemen');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(238, 'DJ', 'Yibuti');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(239, 'ZM', 'Zambia');
INSERT INTO Pais (IdPais,ISO,Descripcion) VALUES(240, 'ZW', 'Zimbabue');
